<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EncryptedTouhid.CompleteAgent.Infrastructure.IntegrationTests</RootNamespace>
    <AssemblyName>EncryptedTouhid.CompleteAgent.Infrastructure.IntegrationTests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.MySql" />
    <PackageReference Include="Testcontainers.CosmosDb" />
    <PackageReference Include="Testcontainers.MongoDb" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EncryptedTouhid.CompleteAgent.Application\EncryptedTouhid.CompleteAgent.Application.csproj" />
    <ProjectReference Include="..\..\src\EncryptedTouhid.CompleteAgent.Infrastructure\EncryptedTouhid.CompleteAgent.Infrastructure.csproj" />
  </ItemGroup>

</Project>
